export default [
  [
    { code: 'Backquote', sym: { en: ['`', '~'], ru: ['ё', 'Ё'] }, element: null },
    { code: 'Digit1',    sym: { en: ['1', '!'], ru: ['1', '!'] }, element: null },
    { code: 'Digit2',    sym: { en: ['2', '@'], ru: ['2', '"'] }, element: null },
    { code: 'Digit3',    sym: { en: ['3', '#'], ru: ['3', '№'] }, element: null },
    { code: 'Digit4',    sym: { en: ['4', '$'], ru: ['4', ';'] }, element: null },
    { code: 'Digit5',    sym: { en: ['5', '%'], ru: ['5', '%'] }, element: null },
    { code: 'Digit6',    sym: { en: ['6', '^'], ru: ['6', ':'] }, element: null },
    { code: 'Digit7',    sym: { en: ['7', '&'], ru: ['7', '?'] }, element: null },
    { code: 'Digit8',    sym: { en: ['8', '*'], ru: ['8', '*'] }, element: null },
    { code: 'Digit9',    sym: { en: ['9', '('], ru: ['9', '('] }, element: null },
    { code: 'Digit0',    sym: { en: ['0', ')'], ru: ['0', ')'] }, element: null },
    { code: 'Minus',     sym: { en: ['-', ')'], ru: ['-', '_'] }, element: null },
    { code: 'Equal',     sym: { en: ['=', ')'], ru: ['=', '+'] }, element: null },
    { code: 'Delete',    sym: 'Del',                              element: null, view: { size: 1 } },
    { code: 'Backspace', sym: { material: 'backspace' },          element: null, view: { size: 2 } },
  ],
  [
    { code: 'Tab',          sym: { material: 'keyboard_tab' },       element: null, view: { size: 2 } },
    { code: 'KeyQ',         sym: { en: ['q', 'Q'], ru: ['й', 'Й'] }, element: null },
    { code: 'KeyW',         sym: { en: ['w', 'W'], ru: ['ц', 'Ц'] }, element: null },
    { code: 'KeyE',         sym: { en: ['e', 'E'], ru: ['у', 'У'] }, element: null },
    { code: 'KeyR',         sym: { en: ['r', 'R'], ru: ['к', 'К'] }, element: null },
    { code: 'KeyT',         sym: { en: ['t', 'T'], ru: ['е', 'Е'] }, element: null },
    { code: 'KeyY',         sym: { en: ['y', 'Y'], ru: ['н', 'Н'] }, element: null },
    { code: 'KeyU',         sym: { en: ['u', 'U'], ru: ['г', 'Г'] }, element: null },
    { code: 'KeyI',         sym: { en: ['i', 'I'], ru: ['ш', 'Ш'] }, element: null },
    { code: 'KeyO',         sym: { en: ['o', 'O'], ru: ['щ', 'Щ'] }, element: null },
    { code: 'KeyP',         sym: { en: ['p', 'P'], ru: ['з', 'З'] }, element: null },
    { code: 'BracketLeft',  sym: { en: ['[', '{'], ru: ['х', 'Х'] }, element: null },
    { code: 'BracketRight', sym: { en: [']', '}'], ru: ['ъ', 'Ъ'] }, element: null },
  ],
  [
    { code: 'CapsLock',  sym: { material: 'keyboard_capslock' },   element: null, view: { size: 2, indicator: true } },
    { code: 'KeyA',      sym: { en: ['a', 'A'], ru: ['ф', 'Ф'] },  element: null },
    { code: 'KeyS',      sym: { en: ['s', 'S'], ru: ['ы', 'Ы'] },  element: null },
    { code: 'KeyD',      sym: { en: ['d', 'D'], ru: ['в', 'В'] },  element: null },
    { code: 'KeyF',      sym: { en: ['f', 'F'], ru: ['а', 'А'] },  element: null },
    { code: 'KeyG',      sym: { en: ['g', 'G'], ru: ['п', 'П'] },  element: null },
    { code: 'KeyH',      sym: { en: ['h', 'H'], ru: ['р', 'Р'] },  element: null },
    { code: 'KeyJ',      sym: { en: ['j', 'J'], ru: ['о', 'О'] },  element: null },
    { code: 'KeyK',      sym: { en: ['k', 'K'], ru: ['л', 'Л'] },  element: null },
    { code: 'KeyL',      sym: { en: ['l', 'L'], ru: ['д', 'Д'] },  element: null },
    { code: 'Semicolon', sym: { en: [';', ':'], ru: ['ж', 'Ж'] },  element: null },
    { code: 'Quote',     sym: { en: ['\'', '"'], ru: ['э', 'Э'] }, element: null },
    { code: 'Enter',     sym: { material: 'keyboard_return' },     element: null, view: { size: 2 } },
  ],
  [
    { code: 'ShiftLeft',  sym: { material: 'shift' },              element: null, view: { size: 2 } },
    { code: 'KeyZ',       sym: { en: ['z', 'Z'], ru: ['я', 'Я'] }, element: null },
    { code: 'KeyX',       sym: { en: ['x', 'X'], ru: ['ч', 'Ч'] }, element: null },
    { code: 'KeyC',       sym: { en: ['c', 'C'], ru: ['с', 'С'] }, element: null },
    { code: 'KeyV',       sym: { en: ['v', 'V'], ru: ['м', 'М'] }, element: null },
    { code: 'KeyB',       sym: { en: ['b', 'B'], ru: ['и', 'И'] }, element: null },
    { code: 'KeyN',       sym: { en: ['n', 'N'], ru: ['т', 'Т'] }, element: null },
    { code: 'KeyM',       sym: { en: ['m', 'M'], ru: ['ь', 'Ь'] }, element: null },
    { code: 'Comma',      sym: { en: [',', '<'], ru: ['б', 'Б'] }, element: null },
    { code: 'Period',     sym: { en: ['.', '>'], ru: ['ю', 'Ю'] }, element: null },
    { code: 'Slash',      sym: { en: ['/', '?'], ru: ['.', ','] }, element: null },
    { code: 'ShiftRight', sym: { material: 'shift' },              element: null, view: { size: 2 } },
  ],
  [
    { code: 'ControlLeft',  sym: 'Ctrl',                          element: null },
    { code: 'OSLeft',       sym: 'Win',                           element: null },
    { code: 'AltLeft',      sym: 'Alt',                           element: null },
    { code: 'Space',        sym: { material: 'space_bar' },       element: null, view: { size: 6 } },
    { code: 'ArrowUp',      sym: { material: 'arrow_drop_up' },   element: null },
    { code: 'ArrowLeft',    sym: { material: 'arrow_left' },      element: null },
    { code: 'ArrowRight',   sym: { material: 'arrow_right' },     element: null },
    { code: 'ArrowDown',    sym: { material: 'arrow_drop_down' }, element: null },
    { code: 'ControlRight', sym: 'Ctrl',                          element: null },
    { code: 'user_clear', sym: { material: 'delete' },            element: null },
  ],
]
